import {
  UPDATE_PLUGIN_SETTING_MUTATION, 
  PLUGIN_SETTING_QUERY, 
  PLUGIN_STORAGE_QUERY, 
  CREATE_PLUGIN_STORAGE_MUTATION
} from './pluginQuery'

import client from './client'

export {
  UPDATE_PLUGIN_SETTING_MUTATION, 
  PLUGIN_SETTING_QUERY, 
  PLUGIN_STORAGE_QUERY, 
  CREATE_PLUGIN_STORAGE_MUTATION, 
  client 
}

